# Generated by Django 3.0.4 on 2021-04-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='gender',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
