# Generated by Django 3.0.4 on 2021-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_donors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
