# Generated by Django 3.0.4 on 2021-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210425_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='car',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
