# Generated by Django 3.0.4 on 2021-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_donors_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
