# Generated by Django 3.0.4 on 2021-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_donors_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
