# Generated by Django 3.0.4 on 2021-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20210426_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
