# Generated by Django 3.0.4 on 2021-04-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20210426_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='img',
        ),
    ]
