# Generated by Django 3.0.4 on 2021-04-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_remove_donors_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
