# Generated by Django 3.0.4 on 2021-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_donors_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='total',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
