# Generated by Django 3.0.4 on 2021-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_donors_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
