# Generated by Django 3.0.4 on 2021-04-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_donors_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='image',
            new_name='pic',
        ),
    ]
