# Generated by Django 3.0.4 on 2021-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20210426_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
