# Generated by Django 3.0.4 on 2021-04-26 06:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20210426_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='bikes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('This is all we know', 'This is all we know'), ('All bright', 'All bright'), ('dark hi dark', 'dark hi dark')], default=0, max_length=43),
            preserve_default=False,
        ),
    ]
