# Generated by Django 3.0.4 on 2021-04-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_donors_bikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='bikes',
        ),
    ]
