# Generated by Django 3.0.4 on 2021-04-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_remove_donors_bikes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donors',
            table=None,
        ),
    ]
