# Generated by Django 3.0.4 on 2021-04-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_auto_20210426_1247'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donors',
            table='blood_donor',
        ),
    ]
