# Generated by Django 3.0.4 on 2021-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_auto_20210426_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donors',
            old_name='car',
            new_name='group',
        ),
        migrations.AddField(
            model_name='donors',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donors',
            name='vehicles',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
