# Generated by Django 3.0.4 on 2021-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_remove_donors_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donors',
            name='boat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donors',
            name='car',
            field=models.BooleanField(default=False),
        ),
    ]
